services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: frkn-backend
    restart: unless-stopped
    environment:
      - PORT=8080
      - DB_PATH=/app/data/data.db
      - STATIC_DIR=/app/static
      - API_SECRET=a681bd9a5e766bbb9f231d2394801326ea10a44449345b7a
    volumes:
      - /opt/frkn-data:/app/data
      - ./frontend/static:/app/static:ro
    ports:
      - "8090:8080"
    mem_limit: 400m
    cpus: '1.5'

